# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160704_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(default=1, upload_to='%Y/%m/%d/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
